<?php /* @var $this Mage_Core_Block_Template */ ?>
<?php if ($websites = $this->getWebsites()): ?>
<p class="switcher"><label for="store_selector"><?php echo $this->__('Choose Store Views:') ?></label>
<select name="store_selector" id="store_selector" multiple="true" size="25">
<?php if ($this->hasDefaultOption()): ?>
    <option value=""><?php echo $this->getDefaultStoreName() ?></option>
<?php endif; ?>
<?php $selectedStores = explode(',', $this->getRequest()->getParam('stores')); ?>
    <?php foreach ($websites as $website): ?>
        <?php $showWebsite = false; ?>
        <?php foreach ($website->getGroups() as $group): ?>
            <?php $showGroup = false; ?>
            <?php foreach ($this->getStores($group) as $store): ?>
                <?php if ($showWebsite == false): ?>
                    <?php $showWebsite = true; ?>
                    <optgroup label="<?php echo $this->escapeHtml($website->getName()) ?>"></optgroup>
                <?php endif; ?>
                <?php if ($showGroup == false): ?>
                    <?php $showGroup = true; ?>
                    <optgroup label="&nbsp;&nbsp;&nbsp;<?php echo $this->escapeHtml($group->getName()) ?>">
                <?php endif; ?>
                <option value="<?php echo $this->escapeHtml($store->getId()) ?>"<?php if (in_array($store->getId(), $selectedStores)): ?> selected="selected"<?php endif; ?>>&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $this->escapeHtml($store->getName()) ?></option>
            <?php endforeach; ?>
            <?php if ($showGroup): ?>
                </optgroup>
            <?php endif; ?>
        <?php endforeach; ?>
    <?php endforeach; ?>
</select>
<?php echo $this->getHintHtml() ?>
<button onclick="switchStores($('store_selector').selectedOptions)"><span><span><?php echo $this->__('Choose') ?></span></span></button>
</p>
<script type="text/javascript">
    function switchStores(values) {
        var stores = [];
        for (var i=0; i<values.length; i++) {
            stores.push(values[i].value);
        }
        var storeParam = stores ? 'stores/' + stores.join() + '/' : '';
    <?php if ($this->getUseConfirm()): ?>
        if (confirm("<?php echo $this->__('Please confirm site switching. All data that hasn\'t been saved will be lost.') ?>")) {
            setLocation('<?php echo $this->getSwitchUrl() ?>' + storeParam);
            return true;
        }
        return false;
    <?php else: ?>
        setLocation('<?php echo $this->getSwitchUrl() ?>' + storeParam);
    <?php endif; ?>
    }
</script>
<?php endif; ?>
